spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.25.151
    port: 5672
    username: admin
    password: admin
  sleuth:
    sampler:
      probability: 1

#server:
 # port: 8001

eureka:
  client:
    service-url:
      #eureka服务器的地址
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      #拉取注册信息间隔时间
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#server:
#  port: 8001
---
spring:
  profiles: item1

server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002
